package com.bankernel.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AdministradorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdministradorAllPropertiesEquals(Administrador expected, Administrador actual) {
        assertAdministradorAutoGeneratedPropertiesEquals(expected, actual);
        assertAdministradorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdministradorAllUpdatablePropertiesEquals(Administrador expected, Administrador actual) {
        assertAdministradorUpdatableFieldsEquals(expected, actual);
        assertAdministradorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdministradorAutoGeneratedPropertiesEquals(Administrador expected, Administrador actual) {
        assertThat(actual)
            .as("Verify Administrador auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdministradorUpdatableFieldsEquals(Administrador expected, Administrador actual) {
        assertThat(actual)
            .as("Verify Administrador relevant properties")
            .satisfies(a -> assertThat(a.getAtivo()).as("check ativo").isEqualTo(expected.getAtivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdministradorUpdatableRelationshipsEquals(Administrador expected, Administrador actual) {
        assertThat(actual)
            .as("Verify Administrador relationships")
            .satisfies(a -> assertThat(a.getEscritorio()).as("check escritorio").isEqualTo(expected.getEscritorio()));
    }
}
