package com.bankernel.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AssinaturaRecorrenciaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssinaturaRecorrenciaAllPropertiesEquals(AssinaturaRecorrencia expected, AssinaturaRecorrencia actual) {
        assertAssinaturaRecorrenciaAutoGeneratedPropertiesEquals(expected, actual);
        assertAssinaturaRecorrenciaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssinaturaRecorrenciaAllUpdatablePropertiesEquals(
        AssinaturaRecorrencia expected,
        AssinaturaRecorrencia actual
    ) {
        assertAssinaturaRecorrenciaUpdatableFieldsEquals(expected, actual);
        assertAssinaturaRecorrenciaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssinaturaRecorrenciaAutoGeneratedPropertiesEquals(
        AssinaturaRecorrencia expected,
        AssinaturaRecorrencia actual
    ) {
        assertThat(actual)
            .as("Verify AssinaturaRecorrencia auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssinaturaRecorrenciaUpdatableFieldsEquals(AssinaturaRecorrencia expected, AssinaturaRecorrencia actual) {
        assertThat(actual)
            .as("Verify AssinaturaRecorrencia relevant properties")
            .satisfies(a -> assertThat(a.getNumeroOrdem()).as("check numeroOrdem").isEqualTo(expected.getNumeroOrdem()))
            .satisfies(a -> assertThat(a.getNumeroReferencia()).as("check numeroReferencia").isEqualTo(expected.getNumeroReferencia()))
            .satisfies(a -> assertThat(a.getDevedorEmail()).as("check devedorEmail").isEqualTo(expected.getDevedorEmail()))
            .satisfies(a -> assertThat(a.getDevedorDocumento()).as("check devedorDocumento").isEqualTo(expected.getDevedorDocumento()))
            .satisfies(a -> assertThat(a.getDevedorNome()).as("check devedorNome").isEqualTo(expected.getDevedorNome()))
            .satisfies(a -> assertThat(a.getDevedorTelefone()).as("check devedorTelefone").isEqualTo(expected.getDevedorTelefone()))
            .satisfies(a -> assertThat(a.getDevedorCep()).as("check devedorCep").isEqualTo(expected.getDevedorCep()))
            .satisfies(a -> assertThat(a.getDevedorUf()).as("check devedorUf").isEqualTo(expected.getDevedorUf()))
            .satisfies(a -> assertThat(a.getDevedorCidade()).as("check devedorCidade").isEqualTo(expected.getDevedorCidade()))
            .satisfies(a -> assertThat(a.getDevedorBairro()).as("check devedorBairro").isEqualTo(expected.getDevedorBairro()))
            .satisfies(a -> assertThat(a.getDevedorEndereco()).as("check devedorEndereco").isEqualTo(expected.getDevedorEndereco()))
            .satisfies(a -> assertThat(a.getAtivo()).as("check ativo").isEqualTo(expected.getAtivo()))
            .satisfies(a -> assertThat(a.getIdProdutoExterno()).as("check idProdutoExterno").isEqualTo(expected.getIdProdutoExterno()))
            .satisfies(a ->
                assertThat(a.getIdentificadorExterno()).as("check identificadorExterno").isEqualTo(expected.getIdentificadorExterno())
            )
            .satisfies(a -> assertThat(a.getNomeProdutoExterno()).as("check nomeProdutoExterno").isEqualTo(expected.getNomeProdutoExterno())
            )
            .satisfies(a -> assertThat(a.getTipo()).as("check tipo").isEqualTo(expected.getTipo()))
            .satisfies(a -> assertThat(a.getTipoPagamento()).as("check tipoPagamento").isEqualTo(expected.getTipoPagamento()))
            .satisfies(a -> assertThat(a.getSituacao()).as("check situacao").isEqualTo(expected.getSituacao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssinaturaRecorrenciaUpdatableRelationshipsEquals(
        AssinaturaRecorrencia expected,
        AssinaturaRecorrencia actual
    ) {
        assertThat(actual)
            .as("Verify AssinaturaRecorrencia relationships")
            .satisfies(a -> assertThat(a.getPlanoRecorrencia()).as("check planoRecorrencia").isEqualTo(expected.getPlanoRecorrencia()))
            .satisfies(a -> assertThat(a.getLinkCobranca()).as("check linkCobranca").isEqualTo(expected.getLinkCobranca()));
    }
}
