package com.bankernel.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BancoReferenciaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBancoReferenciaAllPropertiesEquals(BancoReferencia expected, BancoReferencia actual) {
        assertBancoReferenciaAutoGeneratedPropertiesEquals(expected, actual);
        assertBancoReferenciaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBancoReferenciaAllUpdatablePropertiesEquals(BancoReferencia expected, BancoReferencia actual) {
        assertBancoReferenciaUpdatableFieldsEquals(expected, actual);
        assertBancoReferenciaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBancoReferenciaAutoGeneratedPropertiesEquals(BancoReferencia expected, BancoReferencia actual) {
        assertThat(actual)
            .as("Verify BancoReferencia auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBancoReferenciaUpdatableFieldsEquals(BancoReferencia expected, BancoReferencia actual) {
        assertThat(actual)
            .as("Verify BancoReferencia relevant properties")
            .satisfies(a -> assertThat(a.getCodigo()).as("check codigo").isEqualTo(expected.getCodigo()))
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getIspb()).as("check ispb").isEqualTo(expected.getIspb()))
            .satisfies(a -> assertThat(a.getAtivo()).as("check ativo").isEqualTo(expected.getAtivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBancoReferenciaUpdatableRelationshipsEquals(BancoReferencia expected, BancoReferencia actual) {
        // empty method
    }
}
