package com.bankernel.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BloqueioOperacaoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBloqueioOperacaoAllPropertiesEquals(BloqueioOperacao expected, BloqueioOperacao actual) {
        assertBloqueioOperacaoAutoGeneratedPropertiesEquals(expected, actual);
        assertBloqueioOperacaoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBloqueioOperacaoAllUpdatablePropertiesEquals(BloqueioOperacao expected, BloqueioOperacao actual) {
        assertBloqueioOperacaoUpdatableFieldsEquals(expected, actual);
        assertBloqueioOperacaoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBloqueioOperacaoAutoGeneratedPropertiesEquals(BloqueioOperacao expected, BloqueioOperacao actual) {
        assertThat(actual)
            .as("Verify BloqueioOperacao auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBloqueioOperacaoUpdatableFieldsEquals(BloqueioOperacao expected, BloqueioOperacao actual) {
        assertThat(actual)
            .as("Verify BloqueioOperacao relevant properties")
            .satisfies(a -> assertThat(a.getTipoOperacao()).as("check tipoOperacao").isEqualTo(expected.getTipoOperacao()))
            .satisfies(a -> assertThat(a.getDiaSemana()).as("check diaSemana").isEqualTo(expected.getDiaSemana()))
            .satisfies(a -> assertThat(a.getHoraInicio()).as("check horaInicio").isEqualTo(expected.getHoraInicio()))
            .satisfies(a -> assertThat(a.getHoraFim()).as("check horaFim").isEqualTo(expected.getHoraFim()))
            .satisfies(a -> assertThat(a.getMotivo()).as("check motivo").isEqualTo(expected.getMotivo()))
            .satisfies(a -> assertThat(a.getAtivo()).as("check ativo").isEqualTo(expected.getAtivo()))
            .satisfies(a -> assertThat(a.getTipoExecucao()).as("check tipoExecucao").isEqualTo(expected.getTipoExecucao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBloqueioOperacaoUpdatableRelationshipsEquals(BloqueioOperacao expected, BloqueioOperacao actual) {
        // empty method
    }
}
