package com.bankernel.domain;

import static com.bankernel.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CarteiraAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarteiraAllPropertiesEquals(Carteira expected, Carteira actual) {
        assertCarteiraAutoGeneratedPropertiesEquals(expected, actual);
        assertCarteiraAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarteiraAllUpdatablePropertiesEquals(Carteira expected, Carteira actual) {
        assertCarteiraUpdatableFieldsEquals(expected, actual);
        assertCarteiraUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarteiraAutoGeneratedPropertiesEquals(Carteira expected, Carteira actual) {
        assertThat(actual)
            .as("Verify Carteira auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarteiraUpdatableFieldsEquals(Carteira expected, Carteira actual) {
        assertThat(actual)
            .as("Verify Carteira relevant properties")
            .satisfies(a -> assertThat(a.getSaldo()).as("check saldo").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getSaldo()))
            .satisfies(a ->
                assertThat(a.getLimiteNegativo())
                    .as("check limiteNegativo")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getLimiteNegativo())
            )
            .satisfies(a ->
                assertThat(a.getValorCongelado())
                    .as("check valorCongelado")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getValorCongelado())
            )
            .satisfies(a -> assertThat(a.getNumeroConta()).as("check numeroConta").isEqualTo(expected.getNumeroConta()))
            .satisfies(a -> assertThat(a.getAtiva()).as("check ativa").isEqualTo(expected.getAtiva()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarteiraUpdatableRelationshipsEquals(Carteira expected, Carteira actual) {
        assertThat(actual)
            .as("Verify Carteira relationships")
            .satisfies(a -> assertThat(a.getMoedaCarteira()).as("check moedaCarteira").isEqualTo(expected.getMoedaCarteira()));
    }
}
