package com.bankernel.domain;

import static com.bankernel.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CheckoutAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckoutAllPropertiesEquals(Checkout expected, Checkout actual) {
        assertCheckoutAutoGeneratedPropertiesEquals(expected, actual);
        assertCheckoutAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckoutAllUpdatablePropertiesEquals(Checkout expected, Checkout actual) {
        assertCheckoutUpdatableFieldsEquals(expected, actual);
        assertCheckoutUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckoutAutoGeneratedPropertiesEquals(Checkout expected, Checkout actual) {
        assertThat(actual)
            .as("Verify Checkout auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckoutUpdatableFieldsEquals(Checkout expected, Checkout actual) {
        assertThat(actual)
            .as("Verify Checkout relevant properties")
            .satisfies(a -> assertThat(a.getValor()).as("check valor").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getValor()))
            .satisfies(a ->
                assertThat(a.getValorCreditado())
                    .as("check valorCreditado")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getValorCreditado())
            )
            .satisfies(a ->
                assertThat(a.getValorCreditadoCarteira())
                    .as("check valorCreditadoCarteira")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getValorCreditadoCarteira())
            )
            .satisfies(a -> assertThat(a.getIdProdutoExterno()).as("check idProdutoExterno").isEqualTo(expected.getIdProdutoExterno()))
            .satisfies(a -> assertThat(a.getNomeProdutoExterno()).as("check nomeProdutoExterno").isEqualTo(expected.getNomeProdutoExterno())
            )
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getTipo()).as("check tipo").isEqualTo(expected.getTipo()))
            .satisfies(a ->
                assertThat(a.getDescontoGeral())
                    .as("check descontoGeral")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDescontoGeral())
            )
            .satisfies(a -> assertThat(a.getTipoDesconto()).as("check tipoDesconto").isEqualTo(expected.getTipoDesconto()))
            .satisfies(a -> assertThat(a.getContabilizado()).as("check contabilizado").isEqualTo(expected.getContabilizado()))
            .satisfies(a -> assertThat(a.getNomeUsuarioFixo()).as("check nomeUsuarioFixo").isEqualTo(expected.getNomeUsuarioFixo()))
            .satisfies(a -> assertThat(a.getTokenCheckout()).as("check tokenCheckout").isEqualTo(expected.getTokenCheckout()))
            .satisfies(a -> assertThat(a.getIdExterno()).as("check idExterno").isEqualTo(expected.getIdExterno()))
            .satisfies(a -> assertThat(a.getWebhookNotificado()).as("check webhookNotificado").isEqualTo(expected.getWebhookNotificado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckoutUpdatableRelationshipsEquals(Checkout expected, Checkout actual) {
        assertThat(actual)
            .as("Verify Checkout relationships")
            .satisfies(a -> assertThat(a.getTransacao()).as("check transacao").isEqualTo(expected.getTransacao()))
            .satisfies(a -> assertThat(a.getCarteira()).as("check carteira").isEqualTo(expected.getCarteira()))
            .satisfies(a -> assertThat(a.getCarteiraCreditada()).as("check carteiraCreditada").isEqualTo(expected.getCarteiraCreditada()))
            .satisfies(a -> assertThat(a.getMoedaCarteira()).as("check moedaCarteira").isEqualTo(expected.getMoedaCarteira()))
            .satisfies(a -> assertThat(a.getLinkPagamento()).as("check linkPagamento").isEqualTo(expected.getLinkPagamento()));
    }
}
