package com.bankernel.domain;

import static com.bankernel.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CobrancaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCobrancaAllPropertiesEquals(Cobranca expected, Cobranca actual) {
        assertCobrancaAutoGeneratedPropertiesEquals(expected, actual);
        assertCobrancaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCobrancaAllUpdatablePropertiesEquals(Cobranca expected, Cobranca actual) {
        assertCobrancaUpdatableFieldsEquals(expected, actual);
        assertCobrancaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCobrancaAutoGeneratedPropertiesEquals(Cobranca expected, Cobranca actual) {
        assertThat(actual)
            .as("Verify Cobranca auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCobrancaUpdatableFieldsEquals(Cobranca expected, Cobranca actual) {
        assertThat(actual)
            .as("Verify Cobranca relevant properties")
            .satisfies(a -> assertThat(a.getValor()).as("check valor").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getValor()))
            .satisfies(a ->
                assertThat(a.getValorCreditado())
                    .as("check valorCreditado")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getValorCreditado())
            )
            .satisfies(a ->
                assertThat(a.getValorCreditadoCarteira())
                    .as("check valorCreditadoCarteira")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getValorCreditadoCarteira())
            )
            .satisfies(a -> assertThat(a.getIdProdutoExterno()).as("check idProdutoExterno").isEqualTo(expected.getIdProdutoExterno()))
            .satisfies(a -> assertThat(a.getNomeProdutoExterno()).as("check nomeProdutoExterno").isEqualTo(expected.getNomeProdutoExterno())
            )
            .satisfies(a -> assertThat(a.getSituacao()).as("check situacao").isEqualTo(expected.getSituacao()))
            .satisfies(a -> assertThat(a.getTipo()).as("check tipo").isEqualTo(expected.getTipo()))
            .satisfies(a ->
                assertThat(a.getDescontoGeral())
                    .as("check descontoGeral")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDescontoGeral())
            )
            .satisfies(a -> assertThat(a.getTipoDesconto()).as("check tipoDesconto").isEqualTo(expected.getTipoDesconto()))
            .satisfies(a -> assertThat(a.getContabilizado()).as("check contabilizado").isEqualTo(expected.getContabilizado()))
            .satisfies(a -> assertThat(a.getNomeUsuarioFixo()).as("check nomeUsuarioFixo").isEqualTo(expected.getNomeUsuarioFixo()))
            .satisfies(a -> assertThat(a.getChaveCobranca()).as("check chaveCobranca").isEqualTo(expected.getChaveCobranca()))
            .satisfies(a ->
                assertThat(a.getIdentificadorExterno()).as("check identificadorExterno").isEqualTo(expected.getIdentificadorExterno())
            )
            .satisfies(a -> assertThat(a.getRetornoNotificado()).as("check retornoNotificado").isEqualTo(expected.getRetornoNotificado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCobrancaUpdatableRelationshipsEquals(Cobranca expected, Cobranca actual) {
        assertThat(actual)
            .as("Verify Cobranca relationships")
            .satisfies(a -> assertThat(a.getTransacao()).as("check transacao").isEqualTo(expected.getTransacao()))
            .satisfies(a -> assertThat(a.getCarteira()).as("check carteira").isEqualTo(expected.getCarteira()))
            .satisfies(a -> assertThat(a.getCarteiraCreditada()).as("check carteiraCreditada").isEqualTo(expected.getCarteiraCreditada()))
            .satisfies(a -> assertThat(a.getMoedaCarteira()).as("check moedaCarteira").isEqualTo(expected.getMoedaCarteira()))
            .satisfies(a -> assertThat(a.getLinkCobranca()).as("check linkCobranca").isEqualTo(expected.getLinkCobranca()));
    }
}
