package com.bankernel.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ColaboradorPJAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertColaboradorPJAllPropertiesEquals(ColaboradorPJ expected, ColaboradorPJ actual) {
        assertColaboradorPJAutoGeneratedPropertiesEquals(expected, actual);
        assertColaboradorPJAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertColaboradorPJAllUpdatablePropertiesEquals(ColaboradorPJ expected, ColaboradorPJ actual) {
        assertColaboradorPJUpdatableFieldsEquals(expected, actual);
        assertColaboradorPJUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertColaboradorPJAutoGeneratedPropertiesEquals(ColaboradorPJ expected, ColaboradorPJ actual) {
        assertThat(actual)
            .as("Verify ColaboradorPJ auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertColaboradorPJUpdatableFieldsEquals(ColaboradorPJ expected, ColaboradorPJ actual) {
        assertThat(actual)
            .as("Verify ColaboradorPJ relevant properties")
            .satisfies(a -> assertThat(a.getAtivo()).as("check ativo").isEqualTo(expected.getAtivo()))
            .satisfies(a -> assertThat(a.getDepartamento()).as("check departamento").isEqualTo(expected.getDepartamento()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertColaboradorPJUpdatableRelationshipsEquals(ColaboradorPJ expected, ColaboradorPJ actual) {
        assertThat(actual)
            .as("Verify ColaboradorPJ relationships")
            .satisfies(a -> assertThat(a.getPessoaJuridica()).as("check pessoaJuridica").isEqualTo(expected.getPessoaJuridica()));
    }
}
