package com.bankernel.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ConfiguracaoSistemaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfiguracaoSistemaAllPropertiesEquals(ConfiguracaoSistema expected, ConfiguracaoSistema actual) {
        assertConfiguracaoSistemaAutoGeneratedPropertiesEquals(expected, actual);
        assertConfiguracaoSistemaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfiguracaoSistemaAllUpdatablePropertiesEquals(ConfiguracaoSistema expected, ConfiguracaoSistema actual) {
        assertConfiguracaoSistemaUpdatableFieldsEquals(expected, actual);
        assertConfiguracaoSistemaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfiguracaoSistemaAutoGeneratedPropertiesEquals(ConfiguracaoSistema expected, ConfiguracaoSistema actual) {
        assertThat(actual)
            .as("Verify ConfiguracaoSistema auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfiguracaoSistemaUpdatableFieldsEquals(ConfiguracaoSistema expected, ConfiguracaoSistema actual) {
        assertThat(actual)
            .as("Verify ConfiguracaoSistema relevant properties")
            .satisfies(a -> assertThat(a.getChave()).as("check chave").isEqualTo(expected.getChave()))
            .satisfies(a -> assertThat(a.getValor()).as("check valor").isEqualTo(expected.getValor()))
            .satisfies(a -> assertThat(a.getDescricao()).as("check descricao").isEqualTo(expected.getDescricao()))
            .satisfies(a -> assertThat(a.getTipo()).as("check tipo").isEqualTo(expected.getTipo()))
            .satisfies(a -> assertThat(a.getModulo()).as("check modulo").isEqualTo(expected.getModulo()))
            .satisfies(a -> assertThat(a.getAtiva()).as("check ativa").isEqualTo(expected.getAtiva()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfiguracaoSistemaUpdatableRelationshipsEquals(ConfiguracaoSistema expected, ConfiguracaoSistema actual) {
        // empty method
    }
}
