package com.bankernel.domain;

import static com.bankernel.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ContaContabilAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContaContabilAllPropertiesEquals(ContaContabil expected, ContaContabil actual) {
        assertContaContabilAutoGeneratedPropertiesEquals(expected, actual);
        assertContaContabilAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContaContabilAllUpdatablePropertiesEquals(ContaContabil expected, ContaContabil actual) {
        assertContaContabilUpdatableFieldsEquals(expected, actual);
        assertContaContabilUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContaContabilAutoGeneratedPropertiesEquals(ContaContabil expected, ContaContabil actual) {
        assertThat(actual)
            .as("Verify ContaContabil auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContaContabilUpdatableFieldsEquals(ContaContabil expected, ContaContabil actual) {
        assertThat(actual)
            .as("Verify ContaContabil relevant properties")
            .satisfies(a -> assertThat(a.getCodigo()).as("check codigo").isEqualTo(expected.getCodigo()))
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getSaldo()).as("check saldo").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getSaldo()))
            .satisfies(a -> assertThat(a.getDescricao()).as("check descricao").isEqualTo(expected.getDescricao()))
            .satisfies(a -> assertThat(a.getTipoContaContabil()).as("check tipoContaContabil").isEqualTo(expected.getTipoContaContabil()))
            .satisfies(a ->
                assertThat(a.getCategoriaContaContabil()).as("check categoriaContaContabil").isEqualTo(expected.getCategoriaContaContabil())
            )
            .satisfies(a -> assertThat(a.getAtiva()).as("check ativa").isEqualTo(expected.getAtiva()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContaContabilUpdatableRelationshipsEquals(ContaContabil expected, ContaContabil actual) {
        assertThat(actual)
            .as("Verify ContaContabil relationships")
            .satisfies(a -> assertThat(a.getMoedaCarteira()).as("check moedaCarteira").isEqualTo(expected.getMoedaCarteira()));
    }
}
