package com.bankernel.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ContaBancariaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContaBancariaAllPropertiesEquals(ContaBancaria expected, ContaBancaria actual) {
        assertContaBancariaAutoGeneratedPropertiesEquals(expected, actual);
        assertContaBancariaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContaBancariaAllUpdatablePropertiesEquals(ContaBancaria expected, ContaBancaria actual) {
        assertContaBancariaUpdatableFieldsEquals(expected, actual);
        assertContaBancariaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContaBancariaAutoGeneratedPropertiesEquals(ContaBancaria expected, ContaBancaria actual) {
        assertThat(actual)
            .as("Verify ContaBancaria auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContaBancariaUpdatableFieldsEquals(ContaBancaria expected, ContaBancaria actual) {
        assertThat(actual)
            .as("Verify ContaBancaria relevant properties")
            .satisfies(a -> assertThat(a.getNomeTitular()).as("check nomeTitular").isEqualTo(expected.getNomeTitular()))
            .satisfies(a -> assertThat(a.getNumeroConta()).as("check numeroConta").isEqualTo(expected.getNumeroConta()))
            .satisfies(a -> assertThat(a.getAgencia()).as("check agencia").isEqualTo(expected.getAgencia()))
            .satisfies(a -> assertThat(a.getNomeBanco()).as("check nomeBanco").isEqualTo(expected.getNomeBanco()))
            .satisfies(a -> assertThat(a.getCodigoBanco()).as("check codigoBanco").isEqualTo(expected.getCodigoBanco()))
            .satisfies(a -> assertThat(a.getIspb()).as("check ispb").isEqualTo(expected.getIspb()))
            .satisfies(a -> assertThat(a.getCodigoSwift()).as("check codigoSwift").isEqualTo(expected.getCodigoSwift()))
            .satisfies(a -> assertThat(a.getTipoConta()).as("check tipoConta").isEqualTo(expected.getTipoConta()))
            .satisfies(a -> assertThat(a.getAtiva()).as("check ativa").isEqualTo(expected.getAtiva()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContaBancariaUpdatableRelationshipsEquals(ContaBancaria expected, ContaBancaria actual) {
        assertThat(actual)
            .as("Verify ContaBancaria relationships")
            .satisfies(a -> assertThat(a.getPais()).as("check pais").isEqualTo(expected.getPais()))
            .satisfies(a -> assertThat(a.getMoeda()).as("check moeda").isEqualTo(expected.getMoeda()));
    }
}
