package com.bankernel.domain;

import static com.bankernel.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class DepositoBoletoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepositoBoletoAllPropertiesEquals(DepositoBoleto expected, DepositoBoleto actual) {
        assertDepositoBoletoAutoGeneratedPropertiesEquals(expected, actual);
        assertDepositoBoletoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepositoBoletoAllUpdatablePropertiesEquals(DepositoBoleto expected, DepositoBoleto actual) {
        assertDepositoBoletoUpdatableFieldsEquals(expected, actual);
        assertDepositoBoletoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepositoBoletoAutoGeneratedPropertiesEquals(DepositoBoleto expected, DepositoBoleto actual) {
        assertThat(actual)
            .as("Verify DepositoBoleto auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepositoBoletoUpdatableFieldsEquals(DepositoBoleto expected, DepositoBoleto actual) {
        assertThat(actual)
            .as("Verify DepositoBoleto relevant properties")
            .satisfies(a -> assertThat(a.getTipo()).as("check tipo").isEqualTo(expected.getTipo()))
            .satisfies(a -> assertThat(a.getSituacao()).as("check situacao").isEqualTo(expected.getSituacao()))
            .satisfies(a -> assertThat(a.getCodigoBarras()).as("check codigoBarras").isEqualTo(expected.getCodigoBarras()))
            .satisfies(a -> assertThat(a.getLinhaDigitavel()).as("check linhaDigitavel").isEqualTo(expected.getLinhaDigitavel()))
            .satisfies(a ->
                assertThat(a.getValorOriginal())
                    .as("check valorOriginal")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getValorOriginal())
            )
            .satisfies(a ->
                assertThat(a.getValorCreditado())
                    .as("check valorCreditado")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getValorCreditado())
            )
            .satisfies(a ->
                assertThat(a.getValorRecebido())
                    .as("check valorRecebido")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getValorRecebido())
            )
            .satisfies(a -> assertThat(a.getPagadorNome()).as("check pagadorNome").isEqualTo(expected.getPagadorNome()))
            .satisfies(a -> assertThat(a.getPagadorCpf()).as("check pagadorCpf").isEqualTo(expected.getPagadorCpf()))
            .satisfies(a -> assertThat(a.getPagadorCnpj()).as("check pagadorCnpj").isEqualTo(expected.getPagadorCnpj()))
            .satisfies(a -> assertThat(a.getDataVencimento()).as("check dataVencimento").isEqualTo(expected.getDataVencimento()))
            .satisfies(a -> assertThat(a.getDataRecebimento()).as("check dataRecebimento").isEqualTo(expected.getDataRecebimento()))
            .satisfies(a -> assertThat(a.getContabilizado()).as("check contabilizado").isEqualTo(expected.getContabilizado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepositoBoletoUpdatableRelationshipsEquals(DepositoBoleto expected, DepositoBoleto actual) {
        assertThat(actual)
            .as("Verify DepositoBoleto relationships")
            .satisfies(a -> assertThat(a.getDeposito()).as("check deposito").isEqualTo(expected.getDeposito()))
            .satisfies(a -> assertThat(a.getCarteira()).as("check carteira").isEqualTo(expected.getCarteira()));
    }
}
