package com.bankernel.domain;

import static com.bankernel.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class DepositoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepositoAllPropertiesEquals(Deposito expected, Deposito actual) {
        assertDepositoAutoGeneratedPropertiesEquals(expected, actual);
        assertDepositoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepositoAllUpdatablePropertiesEquals(Deposito expected, Deposito actual) {
        assertDepositoUpdatableFieldsEquals(expected, actual);
        assertDepositoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepositoAutoGeneratedPropertiesEquals(Deposito expected, Deposito actual) {
        assertThat(actual)
            .as("Verify Deposito auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepositoUpdatableFieldsEquals(Deposito expected, Deposito actual) {
        assertThat(actual)
            .as("Verify Deposito relevant properties")
            .satisfies(a -> assertThat(a.getValor()).as("check valor").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getValor()))
            .satisfies(a ->
                assertThat(a.getValorCreditado())
                    .as("check valorCreditado")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getValorCreditado())
            )
            .satisfies(a ->
                assertThat(a.getValorSaldoCarteira())
                    .as("check valorSaldoCarteira")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getValorSaldoCarteira())
            )
            .satisfies(a -> assertThat(a.getTipoDeposito()).as("check tipoDeposito").isEqualTo(expected.getTipoDeposito()))
            .satisfies(a -> assertThat(a.getSituacaoDeposito()).as("check situacaoDeposito").isEqualTo(expected.getSituacaoDeposito()))
            .satisfies(a -> assertThat(a.getNumeroReferencia()).as("check numeroReferencia").isEqualTo(expected.getNumeroReferencia()))
            .satisfies(a -> assertThat(a.getReferenciaExterna()).as("check referenciaExterna").isEqualTo(expected.getReferenciaExterna()))
            .satisfies(a -> assertThat(a.getDescricao()).as("check descricao").isEqualTo(expected.getDescricao()))
            .satisfies(a -> assertThat(a.getMotivoRejeicao()).as("check motivoRejeicao").isEqualTo(expected.getMotivoRejeicao()))
            .satisfies(a -> assertThat(a.getContabilizado()).as("check contabilizado").isEqualTo(expected.getContabilizado()))
            .satisfies(a -> assertThat(a.getNomeUsuarioFixo()).as("check nomeUsuarioFixo").isEqualTo(expected.getNomeUsuarioFixo()))
            .satisfies(a -> assertThat(a.getNumeroParcela()).as("check numeroParcela").isEqualTo(expected.getNumeroParcela()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepositoUpdatableRelationshipsEquals(Deposito expected, Deposito actual) {
        assertThat(actual)
            .as("Verify Deposito relationships")
            .satisfies(a -> assertThat(a.getTransacao()).as("check transacao").isEqualTo(expected.getTransacao()))
            .satisfies(a -> assertThat(a.getCarteira()).as("check carteira").isEqualTo(expected.getCarteira()))
            .satisfies(a -> assertThat(a.getMoedaCarteira()).as("check moedaCarteira").isEqualTo(expected.getMoedaCarteira()))
            .satisfies(a -> assertThat(a.getContaBancaria()).as("check contaBancaria").isEqualTo(expected.getContaBancaria()));
    }
}
