package com.bankernel.domain;

import static com.bankernel.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class DepositoPixAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepositoPixAllPropertiesEquals(DepositoPix expected, DepositoPix actual) {
        assertDepositoPixAutoGeneratedPropertiesEquals(expected, actual);
        assertDepositoPixAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepositoPixAllUpdatablePropertiesEquals(DepositoPix expected, DepositoPix actual) {
        assertDepositoPixUpdatableFieldsEquals(expected, actual);
        assertDepositoPixUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepositoPixAutoGeneratedPropertiesEquals(DepositoPix expected, DepositoPix actual) {
        assertThat(actual)
            .as("Verify DepositoPix auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepositoPixUpdatableFieldsEquals(DepositoPix expected, DepositoPix actual) {
        assertThat(actual)
            .as("Verify DepositoPix relevant properties")
            .satisfies(a -> assertThat(a.getTipo()).as("check tipo").isEqualTo(expected.getTipo()))
            .satisfies(a -> assertThat(a.getSituacao()).as("check situacao").isEqualTo(expected.getSituacao()))
            .satisfies(a ->
                assertThat(a.getValorOriginal())
                    .as("check valorOriginal")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getValorOriginal())
            )
            .satisfies(a ->
                assertThat(a.getValorCreditado())
                    .as("check valorCreditado")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getValorCreditado())
            )
            .satisfies(a ->
                assertThat(a.getValorRecebido())
                    .as("check valorRecebido")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getValorRecebido())
            )
            .satisfies(a -> assertThat(a.getCodigoQr()).as("check codigoQr").isEqualTo(expected.getCodigoQr()))
            .satisfies(a ->
                assertThat(a.getIdentificadorTransacao()).as("check identificadorTransacao").isEqualTo(expected.getIdentificadorTransacao())
            )
            .satisfies(a ->
                assertThat(a.getIdentificadorPontaAPonta())
                    .as("check identificadorPontaAPonta")
                    .isEqualTo(expected.getIdentificadorPontaAPonta())
            )
            .satisfies(a -> assertThat(a.getPagadorNome()).as("check pagadorNome").isEqualTo(expected.getPagadorNome()))
            .satisfies(a -> assertThat(a.getPagadorCpf()).as("check pagadorCpf").isEqualTo(expected.getPagadorCpf()))
            .satisfies(a -> assertThat(a.getPagadorCnpj()).as("check pagadorCnpj").isEqualTo(expected.getPagadorCnpj()))
            .satisfies(a -> assertThat(a.getDataRecebimento()).as("check dataRecebimento").isEqualTo(expected.getDataRecebimento()))
            .satisfies(a -> assertThat(a.getContabilizado()).as("check contabilizado").isEqualTo(expected.getContabilizado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepositoPixUpdatableRelationshipsEquals(DepositoPix expected, DepositoPix actual) {
        assertThat(actual)
            .as("Verify DepositoPix relationships")
            .satisfies(a -> assertThat(a.getDeposito()).as("check deposito").isEqualTo(expected.getDeposito()))
            .satisfies(a -> assertThat(a.getCarteira()).as("check carteira").isEqualTo(expected.getCarteira()));
    }
}
