package com.bankernel.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DocumentoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentoAllPropertiesEquals(Documento expected, Documento actual) {
        assertDocumentoAutoGeneratedPropertiesEquals(expected, actual);
        assertDocumentoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentoAllUpdatablePropertiesEquals(Documento expected, Documento actual) {
        assertDocumentoUpdatableFieldsEquals(expected, actual);
        assertDocumentoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentoAutoGeneratedPropertiesEquals(Documento expected, Documento actual) {
        assertThat(actual)
            .as("Verify Documento auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentoUpdatableFieldsEquals(Documento expected, Documento actual) {
        assertThat(actual)
            .as("Verify Documento relevant properties")
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getTipoArquivo()).as("check tipoArquivo").isEqualTo(expected.getTipoArquivo()))
            .satisfies(a -> assertThat(a.getEndereco()).as("check endereco").isEqualTo(expected.getEndereco()))
            .satisfies(a -> assertThat(a.getTamanho()).as("check tamanho").isEqualTo(expected.getTamanho()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentoUpdatableRelationshipsEquals(Documento expected, Documento actual) {
        // empty method
    }
}
