package com.bankernel.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EscritorioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEscritorioAllPropertiesEquals(Escritorio expected, Escritorio actual) {
        assertEscritorioAutoGeneratedPropertiesEquals(expected, actual);
        assertEscritorioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEscritorioAllUpdatablePropertiesEquals(Escritorio expected, Escritorio actual) {
        assertEscritorioUpdatableFieldsEquals(expected, actual);
        assertEscritorioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEscritorioAutoGeneratedPropertiesEquals(Escritorio expected, Escritorio actual) {
        assertThat(actual)
            .as("Verify Escritorio auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEscritorioUpdatableFieldsEquals(Escritorio expected, Escritorio actual) {
        assertThat(actual)
            .as("Verify Escritorio relevant properties")
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getDescricao()).as("check descricao").isEqualTo(expected.getDescricao()))
            .satisfies(a -> assertThat(a.getAtivo()).as("check ativo").isEqualTo(expected.getAtivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEscritorioUpdatableRelationshipsEquals(Escritorio expected, Escritorio actual) {
        // empty method
    }
}
