package com.bankernel.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FeriadoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeriadoAllPropertiesEquals(Feriado expected, Feriado actual) {
        assertFeriadoAutoGeneratedPropertiesEquals(expected, actual);
        assertFeriadoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeriadoAllUpdatablePropertiesEquals(Feriado expected, Feriado actual) {
        assertFeriadoUpdatableFieldsEquals(expected, actual);
        assertFeriadoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeriadoAutoGeneratedPropertiesEquals(Feriado expected, Feriado actual) {
        assertThat(actual)
            .as("Verify Feriado auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeriadoUpdatableFieldsEquals(Feriado expected, Feriado actual) {
        assertThat(actual)
            .as("Verify Feriado relevant properties")
            .satisfies(a -> assertThat(a.getData()).as("check data").isEqualTo(expected.getData()))
            .satisfies(a -> assertThat(a.getDescricao()).as("check descricao").isEqualTo(expected.getDescricao()))
            .satisfies(a -> assertThat(a.getAtivo()).as("check ativo").isEqualTo(expected.getAtivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeriadoUpdatableRelationshipsEquals(Feriado expected, Feriado actual) {
        // empty method
    }
}
