package com.bankernel.domain;

import static com.bankernel.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class HistoricoOperacaoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoricoOperacaoAllPropertiesEquals(HistoricoOperacao expected, HistoricoOperacao actual) {
        assertHistoricoOperacaoAutoGeneratedPropertiesEquals(expected, actual);
        assertHistoricoOperacaoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoricoOperacaoAllUpdatablePropertiesEquals(HistoricoOperacao expected, HistoricoOperacao actual) {
        assertHistoricoOperacaoUpdatableFieldsEquals(expected, actual);
        assertHistoricoOperacaoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoricoOperacaoAutoGeneratedPropertiesEquals(HistoricoOperacao expected, HistoricoOperacao actual) {
        assertThat(actual)
            .as("Verify HistoricoOperacao auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoricoOperacaoUpdatableFieldsEquals(HistoricoOperacao expected, HistoricoOperacao actual) {
        assertThat(actual)
            .as("Verify HistoricoOperacao relevant properties")
            .satisfies(a -> assertThat(a.getValor()).as("check valor").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getValor()))
            .satisfies(a ->
                assertThat(a.getSaldoApos()).as("check saldoApos").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getSaldoApos())
            )
            .satisfies(a -> assertThat(a.getDescricao()).as("check descricao").isEqualTo(expected.getDescricao()))
            .satisfies(a -> assertThat(a.getTipoSimbolo()).as("check tipoSimbolo").isEqualTo(expected.getTipoSimbolo()))
            .satisfies(a -> assertThat(a.getNumeroReferencia()).as("check numeroReferencia").isEqualTo(expected.getNumeroReferencia()))
            .satisfies(a -> assertThat(a.getTipoHistorico()).as("check tipoHistorico").isEqualTo(expected.getTipoHistorico()))
            .satisfies(a -> assertThat(a.getSituacaoHistorico()).as("check situacaoHistorico").isEqualTo(expected.getSituacaoHistorico()))
            .satisfies(a -> assertThat(a.getTipoEntidadeOrigem()).as("check tipoEntidadeOrigem").isEqualTo(expected.getTipoEntidadeOrigem())
            )
            .satisfies(a -> assertThat(a.getIdEntidadeOrigem()).as("check idEntidadeOrigem").isEqualTo(expected.getIdEntidadeOrigem()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoricoOperacaoUpdatableRelationshipsEquals(HistoricoOperacao expected, HistoricoOperacao actual) {
        assertThat(actual)
            .as("Verify HistoricoOperacao relationships")
            .satisfies(a -> assertThat(a.getTransacao()).as("check transacao").isEqualTo(expected.getTransacao()))
            .satisfies(a -> assertThat(a.getCarteira()).as("check carteira").isEqualTo(expected.getCarteira()));
    }
}
