package com.bankernel.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IntegracaoLogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntegracaoLogAllPropertiesEquals(IntegracaoLog expected, IntegracaoLog actual) {
        assertIntegracaoLogAutoGeneratedPropertiesEquals(expected, actual);
        assertIntegracaoLogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntegracaoLogAllUpdatablePropertiesEquals(IntegracaoLog expected, IntegracaoLog actual) {
        assertIntegracaoLogUpdatableFieldsEquals(expected, actual);
        assertIntegracaoLogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntegracaoLogAutoGeneratedPropertiesEquals(IntegracaoLog expected, IntegracaoLog actual) {
        assertThat(actual)
            .as("Verify IntegracaoLog auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntegracaoLogUpdatableFieldsEquals(IntegracaoLog expected, IntegracaoLog actual) {
        assertThat(actual)
            .as("Verify IntegracaoLog relevant properties")
            .satisfies(a -> assertThat(a.getProvider()).as("check provider").isEqualTo(expected.getProvider()))
            .satisfies(a -> assertThat(a.getTipoIntegracao()).as("check tipoIntegracao").isEqualTo(expected.getTipoIntegracao()))
            .satisfies(a -> assertThat(a.getOperacao()).as("check operacao").isEqualTo(expected.getOperacao()))
            .satisfies(a -> assertThat(a.getRequestBody()).as("check requestBody").isEqualTo(expected.getRequestBody()))
            .satisfies(a -> assertThat(a.getResponseBody()).as("check responseBody").isEqualTo(expected.getResponseBody()))
            .satisfies(a -> assertThat(a.getStatusHttp()).as("check statusHttp").isEqualTo(expected.getStatusHttp()))
            .satisfies(a -> assertThat(a.getSucesso()).as("check sucesso").isEqualTo(expected.getSucesso()))
            .satisfies(a -> assertThat(a.getMensagemErro()).as("check mensagemErro").isEqualTo(expected.getMensagemErro()))
            .satisfies(a -> assertThat(a.getDuracaoMs()).as("check duracaoMs").isEqualTo(expected.getDuracaoMs()))
            .satisfies(a -> assertThat(a.getTipoEntidadeOrigem()).as("check tipoEntidadeOrigem").isEqualTo(expected.getTipoEntidadeOrigem())
            )
            .satisfies(a -> assertThat(a.getIdEntidadeOrigem()).as("check idEntidadeOrigem").isEqualTo(expected.getIdEntidadeOrigem()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntegracaoLogUpdatableRelationshipsEquals(IntegracaoLog expected, IntegracaoLog actual) {
        // empty method
    }
}
