package com.bankernel.domain;

import static com.bankernel.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class LancamentoContabilAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLancamentoContabilAllPropertiesEquals(LancamentoContabil expected, LancamentoContabil actual) {
        assertLancamentoContabilAutoGeneratedPropertiesEquals(expected, actual);
        assertLancamentoContabilAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLancamentoContabilAllUpdatablePropertiesEquals(LancamentoContabil expected, LancamentoContabil actual) {
        assertLancamentoContabilUpdatableFieldsEquals(expected, actual);
        assertLancamentoContabilUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLancamentoContabilAutoGeneratedPropertiesEquals(LancamentoContabil expected, LancamentoContabil actual) {
        assertThat(actual)
            .as("Verify LancamentoContabil auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLancamentoContabilUpdatableFieldsEquals(LancamentoContabil expected, LancamentoContabil actual) {
        assertThat(actual)
            .as("Verify LancamentoContabil relevant properties")
            .satisfies(a -> assertThat(a.getValor()).as("check valor").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getValor()))
            .satisfies(a -> assertThat(a.getTipoLancamento()).as("check tipoLancamento").isEqualTo(expected.getTipoLancamento()))
            .satisfies(a -> assertThat(a.getSinalLancamento()).as("check sinalLancamento").isEqualTo(expected.getSinalLancamento()))
            .satisfies(a -> assertThat(a.getAtivo()).as("check ativo").isEqualTo(expected.getAtivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLancamentoContabilUpdatableRelationshipsEquals(LancamentoContabil expected, LancamentoContabil actual) {
        assertThat(actual)
            .as("Verify LancamentoContabil relationships")
            .satisfies(a -> assertThat(a.getTransacao()).as("check transacao").isEqualTo(expected.getTransacao()))
            .satisfies(a -> assertThat(a.getContaContabil()).as("check contaContabil").isEqualTo(expected.getContaContabil()));
    }
}
