package com.bankernel.domain;

import static com.bankernel.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class LinkPagamentoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLinkPagamentoAllPropertiesEquals(LinkPagamento expected, LinkPagamento actual) {
        assertLinkPagamentoAutoGeneratedPropertiesEquals(expected, actual);
        assertLinkPagamentoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLinkPagamentoAllUpdatablePropertiesEquals(LinkPagamento expected, LinkPagamento actual) {
        assertLinkPagamentoUpdatableFieldsEquals(expected, actual);
        assertLinkPagamentoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLinkPagamentoAutoGeneratedPropertiesEquals(LinkPagamento expected, LinkPagamento actual) {
        assertThat(actual)
            .as("Verify LinkPagamento auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLinkPagamentoUpdatableFieldsEquals(LinkPagamento expected, LinkPagamento actual) {
        assertThat(actual)
            .as("Verify LinkPagamento relevant properties")
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getToken()).as("check token").isEqualTo(expected.getToken()))
            .satisfies(a -> assertThat(a.getChave()).as("check chave").isEqualTo(expected.getChave()))
            .satisfies(a -> assertThat(a.getWebhookUrl()).as("check webhookUrl").isEqualTo(expected.getWebhookUrl()))
            .satisfies(a ->
                assertThat(a.getUrlPagamentoAprovado()).as("check urlPagamentoAprovado").isEqualTo(expected.getUrlPagamentoAprovado())
            )
            .satisfies(a ->
                assertThat(a.getUrlPagamentoCancelado()).as("check urlPagamentoCancelado").isEqualTo(expected.getUrlPagamentoCancelado())
            )
            .satisfies(a ->
                assertThat(a.getUrlPagamentoRejeitado()).as("check urlPagamentoRejeitado").isEqualTo(expected.getUrlPagamentoRejeitado())
            )
            .satisfies(a -> assertThat(a.getTipo()).as("check tipo").isEqualTo(expected.getTipo()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getDataInicio()).as("check dataInicio").isEqualTo(expected.getDataInicio()))
            .satisfies(a -> assertThat(a.getDataFim()).as("check dataFim").isEqualTo(expected.getDataFim()))
            .satisfies(a ->
                assertThat(a.getDesconto()).as("check desconto").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getDesconto())
            )
            .satisfies(a -> assertThat(a.getTipoDesconto()).as("check tipoDesconto").isEqualTo(expected.getTipoDesconto()))
            .satisfies(a ->
                assertThat(a.getValorMinimoPagamento())
                    .as("check valorMinimoPagamento")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getValorMinimoPagamento())
            )
            .satisfies(a -> assertThat(a.getIdExterno()).as("check idExterno").isEqualTo(expected.getIdExterno()))
            .satisfies(a -> assertThat(a.getNumeroReferencia()).as("check numeroReferencia").isEqualTo(expected.getNumeroReferencia()))
            .satisfies(a -> assertThat(a.getAtivo()).as("check ativo").isEqualTo(expected.getAtivo()))
            .satisfies(a -> assertThat(a.getBloqueado()).as("check bloqueado").isEqualTo(expected.getBloqueado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLinkPagamentoUpdatableRelationshipsEquals(LinkPagamento expected, LinkPagamento actual) {
        assertThat(actual)
            .as("Verify LinkPagamento relationships")
            .satisfies(a -> assertThat(a.getMoedaCarteira()).as("check moedaCarteira").isEqualTo(expected.getMoedaCarteira()));
    }
}
