package com.bankernel.domain;

import static com.bankernel.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class LinkCobrancaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLinkCobrancaAllPropertiesEquals(LinkCobranca expected, LinkCobranca actual) {
        assertLinkCobrancaAutoGeneratedPropertiesEquals(expected, actual);
        assertLinkCobrancaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLinkCobrancaAllUpdatablePropertiesEquals(LinkCobranca expected, LinkCobranca actual) {
        assertLinkCobrancaUpdatableFieldsEquals(expected, actual);
        assertLinkCobrancaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLinkCobrancaAutoGeneratedPropertiesEquals(LinkCobranca expected, LinkCobranca actual) {
        assertThat(actual)
            .as("Verify LinkCobranca auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLinkCobrancaUpdatableFieldsEquals(LinkCobranca expected, LinkCobranca actual) {
        assertThat(actual)
            .as("Verify LinkCobranca relevant properties")
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getChaveAcesso()).as("check chaveAcesso").isEqualTo(expected.getChaveAcesso()))
            .satisfies(a -> assertThat(a.getChaveApi()).as("check chaveApi").isEqualTo(expected.getChaveApi()))
            .satisfies(a -> assertThat(a.getUrlRetorno()).as("check urlRetorno").isEqualTo(expected.getUrlRetorno()))
            .satisfies(a ->
                assertThat(a.getUrlPagamentoAprovado()).as("check urlPagamentoAprovado").isEqualTo(expected.getUrlPagamentoAprovado())
            )
            .satisfies(a ->
                assertThat(a.getUrlPagamentoCancelado()).as("check urlPagamentoCancelado").isEqualTo(expected.getUrlPagamentoCancelado())
            )
            .satisfies(a ->
                assertThat(a.getUrlPagamentoRejeitado()).as("check urlPagamentoRejeitado").isEqualTo(expected.getUrlPagamentoRejeitado())
            )
            .satisfies(a -> assertThat(a.getTipo()).as("check tipo").isEqualTo(expected.getTipo()))
            .satisfies(a -> assertThat(a.getSituacao()).as("check situacao").isEqualTo(expected.getSituacao()))
            .satisfies(a -> assertThat(a.getDataInicio()).as("check dataInicio").isEqualTo(expected.getDataInicio()))
            .satisfies(a -> assertThat(a.getDataFim()).as("check dataFim").isEqualTo(expected.getDataFim()))
            .satisfies(a ->
                assertThat(a.getDesconto()).as("check desconto").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getDesconto())
            )
            .satisfies(a -> assertThat(a.getTipoDesconto()).as("check tipoDesconto").isEqualTo(expected.getTipoDesconto()))
            .satisfies(a ->
                assertThat(a.getValorMinimoPagamento())
                    .as("check valorMinimoPagamento")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getValorMinimoPagamento())
            )
            .satisfies(a ->
                assertThat(a.getIdentificadorExterno()).as("check identificadorExterno").isEqualTo(expected.getIdentificadorExterno())
            )
            .satisfies(a -> assertThat(a.getNumeroReferencia()).as("check numeroReferencia").isEqualTo(expected.getNumeroReferencia()))
            .satisfies(a -> assertThat(a.getAtivo()).as("check ativo").isEqualTo(expected.getAtivo()))
            .satisfies(a -> assertThat(a.getBloqueado()).as("check bloqueado").isEqualTo(expected.getBloqueado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLinkCobrancaUpdatableRelationshipsEquals(LinkCobranca expected, LinkCobranca actual) {
        assertThat(actual)
            .as("Verify LinkCobranca relationships")
            .satisfies(a -> assertThat(a.getMoedaCarteira()).as("check moedaCarteira").isEqualTo(expected.getMoedaCarteira()));
    }
}
