package com.bankernel.domain;

import static com.bankernel.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class MoedaCarteiraAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoedaCarteiraAllPropertiesEquals(MoedaCarteira expected, MoedaCarteira actual) {
        assertMoedaCarteiraAutoGeneratedPropertiesEquals(expected, actual);
        assertMoedaCarteiraAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoedaCarteiraAllUpdatablePropertiesEquals(MoedaCarteira expected, MoedaCarteira actual) {
        assertMoedaCarteiraUpdatableFieldsEquals(expected, actual);
        assertMoedaCarteiraUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoedaCarteiraAutoGeneratedPropertiesEquals(MoedaCarteira expected, MoedaCarteira actual) {
        assertThat(actual)
            .as("Verify MoedaCarteira auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoedaCarteiraUpdatableFieldsEquals(MoedaCarteira expected, MoedaCarteira actual) {
        assertThat(actual)
            .as("Verify MoedaCarteira relevant properties")
            .satisfies(a -> assertThat(a.getCodigo()).as("check codigo").isEqualTo(expected.getCodigo()))
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getDescricao()).as("check descricao").isEqualTo(expected.getDescricao()))
            .satisfies(a ->
                assertThat(a.getFatorConversao())
                    .as("check fatorConversao")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getFatorConversao())
            )
            .satisfies(a -> assertThat(a.getAtiva()).as("check ativa").isEqualTo(expected.getAtiva()))
            .satisfies(a -> assertThat(a.getPrincipal()).as("check principal").isEqualTo(expected.getPrincipal()))
            .satisfies(a -> assertThat(a.getCasasDecimais()).as("check casasDecimais").isEqualTo(expected.getCasasDecimais()))
            .satisfies(a -> assertThat(a.getSeparadorMilhar()).as("check separadorMilhar").isEqualTo(expected.getSeparadorMilhar()))
            .satisfies(a -> assertThat(a.getSeparadorDecimal()).as("check separadorDecimal").isEqualTo(expected.getSeparadorDecimal()))
            .satisfies(a -> assertThat(a.getSimbolo()).as("check simbolo").isEqualTo(expected.getSimbolo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoedaCarteiraUpdatableRelationshipsEquals(MoedaCarteira expected, MoedaCarteira actual) {
        assertThat(actual)
            .as("Verify MoedaCarteira relationships")
            .satisfies(a -> assertThat(a.getMoeda()).as("check moeda").isEqualTo(expected.getMoeda()));
    }
}
