package com.bankernel.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MoedaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoedaAllPropertiesEquals(Moeda expected, Moeda actual) {
        assertMoedaAutoGeneratedPropertiesEquals(expected, actual);
        assertMoedaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoedaAllUpdatablePropertiesEquals(Moeda expected, Moeda actual) {
        assertMoedaUpdatableFieldsEquals(expected, actual);
        assertMoedaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoedaAutoGeneratedPropertiesEquals(Moeda expected, Moeda actual) {
        assertThat(actual)
            .as("Verify Moeda auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoedaUpdatableFieldsEquals(Moeda expected, Moeda actual) {
        assertThat(actual)
            .as("Verify Moeda relevant properties")
            .satisfies(a -> assertThat(a.getCodigoMoeda()).as("check codigoMoeda").isEqualTo(expected.getCodigoMoeda()))
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getDescricao()).as("check descricao").isEqualTo(expected.getDescricao()))
            .satisfies(a -> assertThat(a.getAtiva()).as("check ativa").isEqualTo(expected.getAtiva()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoedaUpdatableRelationshipsEquals(Moeda expected, Moeda actual) {
        // empty method
    }
}
