package com.bankernel.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NotificacaoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificacaoAllPropertiesEquals(Notificacao expected, Notificacao actual) {
        assertNotificacaoAutoGeneratedPropertiesEquals(expected, actual);
        assertNotificacaoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificacaoAllUpdatablePropertiesEquals(Notificacao expected, Notificacao actual) {
        assertNotificacaoUpdatableFieldsEquals(expected, actual);
        assertNotificacaoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificacaoAutoGeneratedPropertiesEquals(Notificacao expected, Notificacao actual) {
        assertThat(actual)
            .as("Verify Notificacao auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificacaoUpdatableFieldsEquals(Notificacao expected, Notificacao actual) {
        assertThat(actual)
            .as("Verify Notificacao relevant properties")
            .satisfies(a -> assertThat(a.getTitulo()).as("check titulo").isEqualTo(expected.getTitulo()))
            .satisfies(a -> assertThat(a.getMensagem()).as("check mensagem").isEqualTo(expected.getMensagem()))
            .satisfies(a -> assertThat(a.getTipo()).as("check tipo").isEqualTo(expected.getTipo()))
            .satisfies(a -> assertThat(a.getSituacao()).as("check situacao").isEqualTo(expected.getSituacao()))
            .satisfies(a -> assertThat(a.getCanal()).as("check canal").isEqualTo(expected.getCanal()))
            .satisfies(a -> assertThat(a.getLida()).as("check lida").isEqualTo(expected.getLida()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificacaoUpdatableRelationshipsEquals(Notificacao expected, Notificacao actual) {
        // empty method
    }
}
