package com.bankernel.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PermissaoColaboradorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPermissaoColaboradorAllPropertiesEquals(PermissaoColaborador expected, PermissaoColaborador actual) {
        assertPermissaoColaboradorAutoGeneratedPropertiesEquals(expected, actual);
        assertPermissaoColaboradorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPermissaoColaboradorAllUpdatablePropertiesEquals(PermissaoColaborador expected, PermissaoColaborador actual) {
        assertPermissaoColaboradorUpdatableFieldsEquals(expected, actual);
        assertPermissaoColaboradorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPermissaoColaboradorAutoGeneratedPropertiesEquals(PermissaoColaborador expected, PermissaoColaborador actual) {
        assertThat(actual)
            .as("Verify PermissaoColaborador auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPermissaoColaboradorUpdatableFieldsEquals(PermissaoColaborador expected, PermissaoColaborador actual) {
        assertThat(actual)
            .as("Verify PermissaoColaborador relevant properties")
            .satisfies(a -> assertThat(a.getTipoPermissao()).as("check tipoPermissao").isEqualTo(expected.getTipoPermissao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPermissaoColaboradorUpdatableRelationshipsEquals(PermissaoColaborador expected, PermissaoColaborador actual) {
        assertThat(actual)
            .as("Verify PermissaoColaborador relationships")
            .satisfies(a -> assertThat(a.getColaborador()).as("check colaborador").isEqualTo(expected.getColaborador()))
            .satisfies(a -> assertThat(a.getCarteira()).as("check carteira").isEqualTo(expected.getCarteira()));
    }
}
