package com.bankernel.domain;

import static com.bankernel.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PessoaJuridicaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPessoaJuridicaAllPropertiesEquals(PessoaJuridica expected, PessoaJuridica actual) {
        assertPessoaJuridicaAutoGeneratedPropertiesEquals(expected, actual);
        assertPessoaJuridicaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPessoaJuridicaAllUpdatablePropertiesEquals(PessoaJuridica expected, PessoaJuridica actual) {
        assertPessoaJuridicaUpdatableFieldsEquals(expected, actual);
        assertPessoaJuridicaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPessoaJuridicaAutoGeneratedPropertiesEquals(PessoaJuridica expected, PessoaJuridica actual) {
        assertThat(actual)
            .as("Verify PessoaJuridica auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPessoaJuridicaUpdatableFieldsEquals(PessoaJuridica expected, PessoaJuridica actual) {
        assertThat(actual)
            .as("Verify PessoaJuridica relevant properties")
            .satisfies(a -> assertThat(a.getCnpj()).as("check cnpj").isEqualTo(expected.getCnpj()))
            .satisfies(a -> assertThat(a.getRazaoSocial()).as("check razaoSocial").isEqualTo(expected.getRazaoSocial()))
            .satisfies(a -> assertThat(a.getNomeFantasia()).as("check nomeFantasia").isEqualTo(expected.getNomeFantasia()))
            .satisfies(a -> assertThat(a.getTelefone()).as("check telefone").isEqualTo(expected.getTelefone()))
            .satisfies(a -> assertThat(a.getSitioWeb()).as("check sitioWeb").isEqualTo(expected.getSitioWeb()))
            .satisfies(a -> assertThat(a.getDescricao()).as("check descricao").isEqualTo(expected.getDescricao()))
            .satisfies(a -> assertThat(a.getDataFundacao()).as("check dataFundacao").isEqualTo(expected.getDataFundacao()))
            .satisfies(a ->
                assertThat(a.getCapitalSocial())
                    .as("check capitalSocial")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCapitalSocial())
            )
            .satisfies(a ->
                assertThat(a.getFaturamentoAnual())
                    .as("check faturamentoAnual")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getFaturamentoAnual())
            )
            .satisfies(a ->
                assertThat(a.getMediaMovimentacaoMensal())
                    .as("check mediaMovimentacaoMensal")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMediaMovimentacaoMensal())
            )
            .satisfies(a -> assertThat(a.getTipoDocumento()).as("check tipoDocumento").isEqualTo(expected.getTipoDocumento()))
            .satisfies(a -> assertThat(a.getRegimeTributario()).as("check regimeTributario").isEqualTo(expected.getRegimeTributario()))
            .satisfies(a ->
                assertThat(a.getCodigoNaturezaJuridica()).as("check codigoNaturezaJuridica").isEqualTo(expected.getCodigoNaturezaJuridica())
            )
            .satisfies(a -> assertThat(a.getAtividadePrincipal()).as("check atividadePrincipal").isEqualTo(expected.getAtividadePrincipal())
            )
            .satisfies(a -> assertThat(a.getEmpresaAtiva()).as("check empresaAtiva").isEqualTo(expected.getEmpresaAtiva()))
            .satisfies(a -> assertThat(a.getNivelRisco()).as("check nivelRisco").isEqualTo(expected.getNivelRisco()))
            .satisfies(a -> assertThat(a.getSituacao()).as("check situacao").isEqualTo(expected.getSituacao()))
            .satisfies(a -> assertThat(a.getBloqueioSaque()).as("check bloqueioSaque").isEqualTo(expected.getBloqueioSaque()))
            .satisfies(a ->
                assertThat(a.getCpfRepresentanteLegal()).as("check cpfRepresentanteLegal").isEqualTo(expected.getCpfRepresentanteLegal())
            )
            .satisfies(a -> assertThat(a.getNumeroRegistro()).as("check numeroRegistro").isEqualTo(expected.getNumeroRegistro()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPessoaJuridicaUpdatableRelationshipsEquals(PessoaJuridica expected, PessoaJuridica actual) {
        assertThat(actual)
            .as("Verify PessoaJuridica relationships")
            .satisfies(a -> assertThat(a.getMoedaPrincipal()).as("check moedaPrincipal").isEqualTo(expected.getMoedaPrincipal()))
            .satisfies(a -> assertThat(a.getContratoSocial()).as("check contratoSocial").isEqualTo(expected.getContratoSocial()))
            .satisfies(a -> assertThat(a.getNacionalidade()).as("check nacionalidade").isEqualTo(expected.getNacionalidade()))
            .satisfies(a -> assertThat(a.getTipoNegocio()).as("check tipoNegocio").isEqualTo(expected.getTipoNegocio()))
            .satisfies(a -> assertThat(a.getPlano()).as("check plano").isEqualTo(expected.getPlano()))
            .satisfies(a -> assertThat(a.getEscritorio()).as("check escritorio").isEqualTo(expected.getEscritorio()));
    }
}
