package com.bankernel.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PessoaFisicaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPessoaFisicaAllPropertiesEquals(PessoaFisica expected, PessoaFisica actual) {
        assertPessoaFisicaAutoGeneratedPropertiesEquals(expected, actual);
        assertPessoaFisicaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPessoaFisicaAllUpdatablePropertiesEquals(PessoaFisica expected, PessoaFisica actual) {
        assertPessoaFisicaUpdatableFieldsEquals(expected, actual);
        assertPessoaFisicaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPessoaFisicaAutoGeneratedPropertiesEquals(PessoaFisica expected, PessoaFisica actual) {
        assertThat(actual)
            .as("Verify PessoaFisica auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPessoaFisicaUpdatableFieldsEquals(PessoaFisica expected, PessoaFisica actual) {
        assertThat(actual)
            .as("Verify PessoaFisica relevant properties")
            .satisfies(a -> assertThat(a.getCpf()).as("check cpf").isEqualTo(expected.getCpf()))
            .satisfies(a -> assertThat(a.getNomeCompleto()).as("check nomeCompleto").isEqualTo(expected.getNomeCompleto()))
            .satisfies(a -> assertThat(a.getNomeSocial()).as("check nomeSocial").isEqualTo(expected.getNomeSocial()))
            .satisfies(a -> assertThat(a.getDataNascimento()).as("check dataNascimento").isEqualTo(expected.getDataNascimento()))
            .satisfies(a -> assertThat(a.getGenero()).as("check genero").isEqualTo(expected.getGenero()))
            .satisfies(a -> assertThat(a.getNomeMae()).as("check nomeMae").isEqualTo(expected.getNomeMae()))
            .satisfies(a -> assertThat(a.getTelefone()).as("check telefone").isEqualTo(expected.getTelefone()))
            .satisfies(a -> assertThat(a.getTelefoneVerificado()).as("check telefoneVerificado").isEqualTo(expected.getTelefoneVerificado())
            )
            .satisfies(a -> assertThat(a.getNivelRisco()).as("check nivelRisco").isEqualTo(expected.getNivelRisco()))
            .satisfies(a -> assertThat(a.getSituacao()).as("check situacao").isEqualTo(expected.getSituacao()))
            .satisfies(a -> assertThat(a.getBloqueioSaque()).as("check bloqueioSaque").isEqualTo(expected.getBloqueioSaque()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPessoaFisicaUpdatableRelationshipsEquals(PessoaFisica expected, PessoaFisica actual) {
        assertThat(actual)
            .as("Verify PessoaFisica relationships")
            .satisfies(a -> assertThat(a.getMoedaPrincipal()).as("check moedaPrincipal").isEqualTo(expected.getMoedaPrincipal()))
            .satisfies(a -> assertThat(a.getNacionalidade()).as("check nacionalidade").isEqualTo(expected.getNacionalidade()))
            .satisfies(a -> assertThat(a.getProfissao()).as("check profissao").isEqualTo(expected.getProfissao()))
            .satisfies(a -> assertThat(a.getPlano()).as("check plano").isEqualTo(expected.getPlano()))
            .satisfies(a -> assertThat(a.getEscritorio()).as("check escritorio").isEqualTo(expected.getEscritorio()));
    }
}
