package com.bankernel.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PlanoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanoAllPropertiesEquals(Plano expected, Plano actual) {
        assertPlanoAutoGeneratedPropertiesEquals(expected, actual);
        assertPlanoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanoAllUpdatablePropertiesEquals(Plano expected, Plano actual) {
        assertPlanoUpdatableFieldsEquals(expected, actual);
        assertPlanoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanoAutoGeneratedPropertiesEquals(Plano expected, Plano actual) {
        assertThat(actual)
            .as("Verify Plano auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanoUpdatableFieldsEquals(Plano expected, Plano actual) {
        assertThat(actual)
            .as("Verify Plano relevant properties")
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getDescricao()).as("check descricao").isEqualTo(expected.getDescricao()))
            .satisfies(a -> assertThat(a.getAtivo()).as("check ativo").isEqualTo(expected.getAtivo()))
            .satisfies(a -> assertThat(a.getPadrao()).as("check padrao").isEqualTo(expected.getPadrao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanoUpdatableRelationshipsEquals(Plano expected, Plano actual) {
        // empty method
    }
}
