package com.bankernel.domain;

import static com.bankernel.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PlanoRecorrenciaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanoRecorrenciaAllPropertiesEquals(PlanoRecorrencia expected, PlanoRecorrencia actual) {
        assertPlanoRecorrenciaAutoGeneratedPropertiesEquals(expected, actual);
        assertPlanoRecorrenciaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanoRecorrenciaAllUpdatablePropertiesEquals(PlanoRecorrencia expected, PlanoRecorrencia actual) {
        assertPlanoRecorrenciaUpdatableFieldsEquals(expected, actual);
        assertPlanoRecorrenciaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanoRecorrenciaAutoGeneratedPropertiesEquals(PlanoRecorrencia expected, PlanoRecorrencia actual) {
        assertThat(actual)
            .as("Verify PlanoRecorrencia auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanoRecorrenciaUpdatableFieldsEquals(PlanoRecorrencia expected, PlanoRecorrencia actual) {
        assertThat(actual)
            .as("Verify PlanoRecorrencia relevant properties")
            .satisfies(a ->
                assertThat(a.getIdentificadorExterno()).as("check identificadorExterno").isEqualTo(expected.getIdentificadorExterno())
            )
            .satisfies(a -> assertThat(a.getNumeroReferencia()).as("check numeroReferencia").isEqualTo(expected.getNumeroReferencia()))
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getDescricao()).as("check descricao").isEqualTo(expected.getDescricao()))
            .satisfies(a -> assertThat(a.getValor()).as("check valor").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getValor()))
            .satisfies(a -> assertThat(a.getDiasTeste()).as("check diasTeste").isEqualTo(expected.getDiasTeste()))
            .satisfies(a -> assertThat(a.getIntervalo()).as("check intervalo").isEqualTo(expected.getIntervalo()))
            .satisfies(a -> assertThat(a.getParcelas()).as("check parcelas").isEqualTo(expected.getParcelas()))
            .satisfies(a -> assertThat(a.getTentativas()).as("check tentativas").isEqualTo(expected.getTentativas()))
            .satisfies(a -> assertThat(a.getAtivo()).as("check ativo").isEqualTo(expected.getAtivo()))
            .satisfies(a -> assertThat(a.getMetodoPagamento()).as("check metodoPagamento").isEqualTo(expected.getMetodoPagamento()))
            .satisfies(a -> assertThat(a.getTipoPlano()).as("check tipoPlano").isEqualTo(expected.getTipoPlano()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanoRecorrenciaUpdatableRelationshipsEquals(PlanoRecorrencia expected, PlanoRecorrencia actual) {
        assertThat(actual)
            .as("Verify PlanoRecorrencia relationships")
            .satisfies(a -> assertThat(a.getLinkCobranca()).as("check linkCobranca").isEqualTo(expected.getLinkCobranca()));
    }
}
