package com.bankernel.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProfissaoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfissaoAllPropertiesEquals(Profissao expected, Profissao actual) {
        assertProfissaoAutoGeneratedPropertiesEquals(expected, actual);
        assertProfissaoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfissaoAllUpdatablePropertiesEquals(Profissao expected, Profissao actual) {
        assertProfissaoUpdatableFieldsEquals(expected, actual);
        assertProfissaoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfissaoAutoGeneratedPropertiesEquals(Profissao expected, Profissao actual) {
        assertThat(actual)
            .as("Verify Profissao auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfissaoUpdatableFieldsEquals(Profissao expected, Profissao actual) {
        assertThat(actual)
            .as("Verify Profissao relevant properties")
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getAtiva()).as("check ativa").isEqualTo(expected.getAtiva()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfissaoUpdatableRelationshipsEquals(Profissao expected, Profissao actual) {
        // empty method
    }
}
