package com.bankernel.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RegistroIntegracaoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegistroIntegracaoAllPropertiesEquals(RegistroIntegracao expected, RegistroIntegracao actual) {
        assertRegistroIntegracaoAutoGeneratedPropertiesEquals(expected, actual);
        assertRegistroIntegracaoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegistroIntegracaoAllUpdatablePropertiesEquals(RegistroIntegracao expected, RegistroIntegracao actual) {
        assertRegistroIntegracaoUpdatableFieldsEquals(expected, actual);
        assertRegistroIntegracaoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegistroIntegracaoAutoGeneratedPropertiesEquals(RegistroIntegracao expected, RegistroIntegracao actual) {
        assertThat(actual)
            .as("Verify RegistroIntegracao auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegistroIntegracaoUpdatableFieldsEquals(RegistroIntegracao expected, RegistroIntegracao actual) {
        assertThat(actual)
            .as("Verify RegistroIntegracao relevant properties")
            .satisfies(a -> assertThat(a.getFornecedor()).as("check fornecedor").isEqualTo(expected.getFornecedor()))
            .satisfies(a -> assertThat(a.getTipoIntegracao()).as("check tipoIntegracao").isEqualTo(expected.getTipoIntegracao()))
            .satisfies(a -> assertThat(a.getOperacao()).as("check operacao").isEqualTo(expected.getOperacao()))
            .satisfies(a -> assertThat(a.getCorpoRequisicao()).as("check corpoRequisicao").isEqualTo(expected.getCorpoRequisicao()))
            .satisfies(a -> assertThat(a.getCorpoResposta()).as("check corpoResposta").isEqualTo(expected.getCorpoResposta()))
            .satisfies(a -> assertThat(a.getCodigoHttp()).as("check codigoHttp").isEqualTo(expected.getCodigoHttp()))
            .satisfies(a -> assertThat(a.getSucesso()).as("check sucesso").isEqualTo(expected.getSucesso()))
            .satisfies(a -> assertThat(a.getMensagemErro()).as("check mensagemErro").isEqualTo(expected.getMensagemErro()))
            .satisfies(a ->
                assertThat(a.getDuracaoMilissegundos()).as("check duracaoMilissegundos").isEqualTo(expected.getDuracaoMilissegundos())
            )
            .satisfies(a -> assertThat(a.getTipoEntidadeOrigem()).as("check tipoEntidadeOrigem").isEqualTo(expected.getTipoEntidadeOrigem())
            )
            .satisfies(a -> assertThat(a.getIdEntidadeOrigem()).as("check idEntidadeOrigem").isEqualTo(expected.getIdEntidadeOrigem()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegistroIntegracaoUpdatableRelationshipsEquals(RegistroIntegracao expected, RegistroIntegracao actual) {
        // empty method
    }
}
