package com.bankernel.domain;

import static com.bankernel.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class SaquePixAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaquePixAllPropertiesEquals(SaquePix expected, SaquePix actual) {
        assertSaquePixAutoGeneratedPropertiesEquals(expected, actual);
        assertSaquePixAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaquePixAllUpdatablePropertiesEquals(SaquePix expected, SaquePix actual) {
        assertSaquePixUpdatableFieldsEquals(expected, actual);
        assertSaquePixUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaquePixAutoGeneratedPropertiesEquals(SaquePix expected, SaquePix actual) {
        assertThat(actual)
            .as("Verify SaquePix auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaquePixUpdatableFieldsEquals(SaquePix expected, SaquePix actual) {
        assertThat(actual)
            .as("Verify SaquePix relevant properties")
            .satisfies(a -> assertThat(a.getTipo()).as("check tipo").isEqualTo(expected.getTipo()))
            .satisfies(a -> assertThat(a.getSituacao()).as("check situacao").isEqualTo(expected.getSituacao()))
            .satisfies(a ->
                assertThat(a.getValorSaque())
                    .as("check valorSaque")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getValorSaque())
            )
            .satisfies(a ->
                assertThat(a.getValorEnviado())
                    .as("check valorEnviado")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getValorEnviado())
            )
            .satisfies(a ->
                assertThat(a.getIdentificadorPagamento()).as("check identificadorPagamento").isEqualTo(expected.getIdentificadorPagamento())
            )
            .satisfies(a ->
                assertThat(a.getIdentificadorPontaAPonta())
                    .as("check identificadorPontaAPonta")
                    .isEqualTo(expected.getIdentificadorPontaAPonta())
            )
            .satisfies(a -> assertThat(a.getCampoLivre()).as("check campoLivre").isEqualTo(expected.getCampoLivre()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaquePixUpdatableRelationshipsEquals(SaquePix expected, SaquePix actual) {
        assertThat(actual)
            .as("Verify SaquePix relationships")
            .satisfies(a -> assertThat(a.getSaque()).as("check saque").isEqualTo(expected.getSaque()));
    }
}
