package com.bankernel.domain;

import static com.bankernel.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class SaqueAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaqueAllPropertiesEquals(Saque expected, Saque actual) {
        assertSaqueAutoGeneratedPropertiesEquals(expected, actual);
        assertSaqueAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaqueAllUpdatablePropertiesEquals(Saque expected, Saque actual) {
        assertSaqueUpdatableFieldsEquals(expected, actual);
        assertSaqueUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaqueAutoGeneratedPropertiesEquals(Saque expected, Saque actual) {
        assertThat(actual)
            .as("Verify Saque auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaqueUpdatableFieldsEquals(Saque expected, Saque actual) {
        assertThat(actual)
            .as("Verify Saque relevant properties")
            .satisfies(a ->
                assertThat(a.getValorSaque())
                    .as("check valorSaque")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getValorSaque())
            )
            .satisfies(a ->
                assertThat(a.getValorEnviado())
                    .as("check valorEnviado")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getValorEnviado())
            )
            .satisfies(a -> assertThat(a.getDescricao()).as("check descricao").isEqualTo(expected.getDescricao()))
            .satisfies(a -> assertThat(a.getTipoSaque()).as("check tipoSaque").isEqualTo(expected.getTipoSaque()))
            .satisfies(a -> assertThat(a.getSituacaoSaque()).as("check situacaoSaque").isEqualTo(expected.getSituacaoSaque()))
            .satisfies(a -> assertThat(a.getNumeroReferencia()).as("check numeroReferencia").isEqualTo(expected.getNumeroReferencia()))
            .satisfies(a -> assertThat(a.getMotivoRejeicao()).as("check motivoRejeicao").isEqualTo(expected.getMotivoRejeicao()))
            .satisfies(a -> assertThat(a.getContabilizado()).as("check contabilizado").isEqualTo(expected.getContabilizado()))
            .satisfies(a -> assertThat(a.getNomeUsuarioFixo()).as("check nomeUsuarioFixo").isEqualTo(expected.getNomeUsuarioFixo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaqueUpdatableRelationshipsEquals(Saque expected, Saque actual) {
        assertThat(actual)
            .as("Verify Saque relationships")
            .satisfies(a -> assertThat(a.getTransacao()).as("check transacao").isEqualTo(expected.getTransacao()))
            .satisfies(a -> assertThat(a.getTransacaoEstorno()).as("check transacaoEstorno").isEqualTo(expected.getTransacaoEstorno()))
            .satisfies(a -> assertThat(a.getCarteira()).as("check carteira").isEqualTo(expected.getCarteira()))
            .satisfies(a -> assertThat(a.getMoedaCarteira()).as("check moedaCarteira").isEqualTo(expected.getMoedaCarteira()))
            .satisfies(a ->
                assertThat(a.getContaBancariaDestino()).as("check contaBancariaDestino").isEqualTo(expected.getContaBancariaDestino())
            )
            .satisfies(a -> assertThat(a.getEscritorio()).as("check escritorio").isEqualTo(expected.getEscritorio()));
    }
}
