package com.bankernel.domain;

import static com.bankernel.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class SaqueBoletoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaqueBoletoAllPropertiesEquals(SaqueBoleto expected, SaqueBoleto actual) {
        assertSaqueBoletoAutoGeneratedPropertiesEquals(expected, actual);
        assertSaqueBoletoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaqueBoletoAllUpdatablePropertiesEquals(SaqueBoleto expected, SaqueBoleto actual) {
        assertSaqueBoletoUpdatableFieldsEquals(expected, actual);
        assertSaqueBoletoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaqueBoletoAutoGeneratedPropertiesEquals(SaqueBoleto expected, SaqueBoleto actual) {
        assertThat(actual)
            .as("Verify SaqueBoleto auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaqueBoletoUpdatableFieldsEquals(SaqueBoleto expected, SaqueBoleto actual) {
        assertThat(actual)
            .as("Verify SaqueBoleto relevant properties")
            .satisfies(a -> assertThat(a.getTipo()).as("check tipo").isEqualTo(expected.getTipo()))
            .satisfies(a -> assertThat(a.getSituacao()).as("check situacao").isEqualTo(expected.getSituacao()))
            .satisfies(a ->
                assertThat(a.getValorSaque())
                    .as("check valorSaque")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getValorSaque())
            )
            .satisfies(a ->
                assertThat(a.getValorEnviado())
                    .as("check valorEnviado")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getValorEnviado())
            )
            .satisfies(a -> assertThat(a.getCodigoBarras()).as("check codigoBarras").isEqualTo(expected.getCodigoBarras()))
            .satisfies(a -> assertThat(a.getCampoLivre()).as("check campoLivre").isEqualTo(expected.getCampoLivre()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaqueBoletoUpdatableRelationshipsEquals(SaqueBoleto expected, SaqueBoleto actual) {
        assertThat(actual)
            .as("Verify SaqueBoleto relationships")
            .satisfies(a -> assertThat(a.getSaque()).as("check saque").isEqualTo(expected.getSaque()));
    }
}
