package com.bankernel.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TipoOperacaoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoOperacaoAllPropertiesEquals(TipoOperacao expected, TipoOperacao actual) {
        assertTipoOperacaoAutoGeneratedPropertiesEquals(expected, actual);
        assertTipoOperacaoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoOperacaoAllUpdatablePropertiesEquals(TipoOperacao expected, TipoOperacao actual) {
        assertTipoOperacaoUpdatableFieldsEquals(expected, actual);
        assertTipoOperacaoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoOperacaoAutoGeneratedPropertiesEquals(TipoOperacao expected, TipoOperacao actual) {
        assertThat(actual)
            .as("Verify TipoOperacao auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoOperacaoUpdatableFieldsEquals(TipoOperacao expected, TipoOperacao actual) {
        assertThat(actual)
            .as("Verify TipoOperacao relevant properties")
            .satisfies(a -> assertThat(a.getCodigo()).as("check codigo").isEqualTo(expected.getCodigo()))
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getDescricao()).as("check descricao").isEqualTo(expected.getDescricao()))
            .satisfies(a -> assertThat(a.getAtivo()).as("check ativo").isEqualTo(expected.getAtivo()))
            .satisfies(a -> assertThat(a.getSinalCredito()).as("check sinalCredito").isEqualTo(expected.getSinalCredito()))
            .satisfies(a -> assertThat(a.getSinalDebito()).as("check sinalDebito").isEqualTo(expected.getSinalDebito()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoOperacaoUpdatableRelationshipsEquals(TipoOperacao expected, TipoOperacao actual) {
        assertThat(actual)
            .as("Verify TipoOperacao relationships")
            .satisfies(a -> assertThat(a.getContaCredito()).as("check contaCredito").isEqualTo(expected.getContaCredito()))
            .satisfies(a -> assertThat(a.getContaDebito()).as("check contaDebito").isEqualTo(expected.getContaDebito()))
            .satisfies(a -> assertThat(a.getMoedaCarteira()).as("check moedaCarteira").isEqualTo(expected.getMoedaCarteira()));
    }
}
