package com.bankernel.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TipoNegocioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoNegocioAllPropertiesEquals(TipoNegocio expected, TipoNegocio actual) {
        assertTipoNegocioAutoGeneratedPropertiesEquals(expected, actual);
        assertTipoNegocioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoNegocioAllUpdatablePropertiesEquals(TipoNegocio expected, TipoNegocio actual) {
        assertTipoNegocioUpdatableFieldsEquals(expected, actual);
        assertTipoNegocioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoNegocioAutoGeneratedPropertiesEquals(TipoNegocio expected, TipoNegocio actual) {
        assertThat(actual)
            .as("Verify TipoNegocio auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoNegocioUpdatableFieldsEquals(TipoNegocio expected, TipoNegocio actual) {
        assertThat(actual)
            .as("Verify TipoNegocio relevant properties")
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getAtivo()).as("check ativo").isEqualTo(expected.getAtivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoNegocioUpdatableRelationshipsEquals(TipoNegocio expected, TipoNegocio actual) {
        // empty method
    }
}
