package com.bankernel.domain;

import static com.bankernel.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class TransacaoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransacaoAllPropertiesEquals(Transacao expected, Transacao actual) {
        assertTransacaoAutoGeneratedPropertiesEquals(expected, actual);
        assertTransacaoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransacaoAllUpdatablePropertiesEquals(Transacao expected, Transacao actual) {
        assertTransacaoUpdatableFieldsEquals(expected, actual);
        assertTransacaoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransacaoAutoGeneratedPropertiesEquals(Transacao expected, Transacao actual) {
        assertThat(actual)
            .as("Verify Transacao auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransacaoUpdatableFieldsEquals(Transacao expected, Transacao actual) {
        assertThat(actual)
            .as("Verify Transacao relevant properties")
            .satisfies(a ->
                assertThat(a.getValorEnviado())
                    .as("check valorEnviado")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getValorEnviado())
            )
            .satisfies(a ->
                assertThat(a.getValorRecebido())
                    .as("check valorRecebido")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getValorRecebido())
            )
            .satisfies(a -> assertThat(a.getDescricao()).as("check descricao").isEqualTo(expected.getDescricao()))
            .satisfies(a -> assertThat(a.getEstornada()).as("check estornada").isEqualTo(expected.getEstornada()))
            .satisfies(a -> assertThat(a.getTipoTransacao()).as("check tipoTransacao").isEqualTo(expected.getTipoTransacao()))
            .satisfies(a -> assertThat(a.getTipoPagamento()).as("check tipoPagamento").isEqualTo(expected.getTipoPagamento()))
            .satisfies(a -> assertThat(a.getSituacao()).as("check situacao").isEqualTo(expected.getSituacao()))
            .satisfies(a -> assertThat(a.getAtiva()).as("check ativa").isEqualTo(expected.getAtiva()))
            .satisfies(a -> assertThat(a.getTipoEntidadeOrigem()).as("check tipoEntidadeOrigem").isEqualTo(expected.getTipoEntidadeOrigem())
            )
            .satisfies(a -> assertThat(a.getIdEntidadeOrigem()).as("check idEntidadeOrigem").isEqualTo(expected.getIdEntidadeOrigem()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransacaoUpdatableRelationshipsEquals(Transacao expected, Transacao actual) {
        assertThat(actual)
            .as("Verify Transacao relationships")
            .satisfies(a -> assertThat(a.getCarteiraOrigem()).as("check carteiraOrigem").isEqualTo(expected.getCarteiraOrigem()))
            .satisfies(a -> assertThat(a.getCarteiraDestino()).as("check carteiraDestino").isEqualTo(expected.getCarteiraDestino()))
            .satisfies(a -> assertThat(a.getMoedaOrigem()).as("check moedaOrigem").isEqualTo(expected.getMoedaOrigem()))
            .satisfies(a -> assertThat(a.getMoedaDestino()).as("check moedaDestino").isEqualTo(expected.getMoedaDestino()));
    }
}
