package com.bankernel.domain;

import static com.bankernel.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class TransferenciaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransferenciaAllPropertiesEquals(Transferencia expected, Transferencia actual) {
        assertTransferenciaAutoGeneratedPropertiesEquals(expected, actual);
        assertTransferenciaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransferenciaAllUpdatablePropertiesEquals(Transferencia expected, Transferencia actual) {
        assertTransferenciaUpdatableFieldsEquals(expected, actual);
        assertTransferenciaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransferenciaAutoGeneratedPropertiesEquals(Transferencia expected, Transferencia actual) {
        assertThat(actual)
            .as("Verify Transferencia auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransferenciaUpdatableFieldsEquals(Transferencia expected, Transferencia actual) {
        assertThat(actual)
            .as("Verify Transferencia relevant properties")
            .satisfies(a -> assertThat(a.getValor()).as("check valor").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getValor()))
            .satisfies(a -> assertThat(a.getChaveInterna()).as("check chaveInterna").isEqualTo(expected.getChaveInterna()))
            .satisfies(a -> assertThat(a.getTipoChave()).as("check tipoChave").isEqualTo(expected.getTipoChave()))
            .satisfies(a -> assertThat(a.getSituacao()).as("check situacao").isEqualTo(expected.getSituacao()))
            .satisfies(a -> assertThat(a.getDescricao()).as("check descricao").isEqualTo(expected.getDescricao()))
            .satisfies(a -> assertThat(a.getMotivoRejeicao()).as("check motivoRejeicao").isEqualTo(expected.getMotivoRejeicao()))
            .satisfies(a -> assertThat(a.getNumeroReferencia()).as("check numeroReferencia").isEqualTo(expected.getNumeroReferencia()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransferenciaUpdatableRelationshipsEquals(Transferencia expected, Transferencia actual) {
        assertThat(actual)
            .as("Verify Transferencia relationships")
            .satisfies(a -> assertThat(a.getTransacao()).as("check transacao").isEqualTo(expected.getTransacao()))
            .satisfies(a -> assertThat(a.getCarteiraOrigem()).as("check carteiraOrigem").isEqualTo(expected.getCarteiraOrigem()))
            .satisfies(a -> assertThat(a.getCarteiraDestino()).as("check carteiraDestino").isEqualTo(expected.getCarteiraDestino()))
            .satisfies(a -> assertThat(a.getMoedaCarteira()).as("check moedaCarteira").isEqualTo(expected.getMoedaCarteira()));
    }
}
